### ISSUE TITLE
Will this work in Arduino Uno ?

### ISSUE THREAD

**Issue by uajith** [Rahul24-06/Mini-Piano#1]
What are the changes required if it has to work in Arduino Uno ?

**Comment by Rahul24-06** [comment]
Hi there, 
You don't have to make any modification to the code as both Arduino Uno and Arduino Nano uses the same controller. If you face any issues further, please feel free to share it. 

Thanks, 
Rahul Khanna D

**Comment by uajith** [comment]
Thank you..
